Repository SOPT-all/35-COLLABORATION-iOS-TWOSOMEHEART, pull requests merged in 2024-11, with the labels that each got.

#6 [FEAT] 공용 컴포넌트 구현 (#3)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/UILabel+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/UIStackView+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Resources/Assets.xcassets/Colors/tsBlack.colorset/Contents.json
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Resources/Assets.xcassets/Colors/tsOrange.colorset/Contents.json
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Resources/Assets.xcassets/Colors/tsWhite.colorset/Contents.json
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CounterView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomSegmentControlView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Enums/CounterType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Enums/SegmentType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseNavViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseViewController.swift
Labels: 🫐 feature, 🍓 수민

#9 [FEAT] 메뉴 옵션 UI 구현 (#4)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/ReusableIdentifier+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/UILabel+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/UIStackView+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CounterView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomSegmentControlView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/Controller/MenuOptionViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/Model/MenuOption.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/Model/MenuOptionHeader.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/Protocol/CounterViewDelegate.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/HeaderView/MenuOptionHeaderView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/TableViewCell/MenuOptionDrizzleCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/TableViewCell/MenuOptionShotCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/TableViewCell/MenuOptionSyrupCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/TableViewCell/MenuOptionWhippedCreamCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/View/Type/MenuOptionSectionType.swift
Labels: 🫐 feature, 🍍범수

#10 [FEAT] 마이 투썸 UI 구현 (#5)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/Int+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Model/MyMenuItem.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/Cell/MyMenuCollectionViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuHeaderView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuModalView.swift
Labels: 🫐 feature, 🍒 예지

#14 [FEAT] 커스텀 알림창 UI 구현 (#13)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomAlertViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuHeaderView.swift
Labels: 🫐 feature, 🍍범수

#16 [FEAT] 메뉴 디테일 UI 구현 (#8)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/String+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Controller/MenuDetailViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Model/MenuDetail.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Type/CautionType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Type/MenuDetailSectionType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Type/MenuStatusType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/AllergyTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/MenuInfoTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/NutritionHeaderTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/NutritionInfoTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/MenuDetailBottomView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuModalView.swift
Labels: 🫐 feature, 🍒 예지

#17 [FEAT] 모달 뷰 UI 구현 (#7)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Extensions/UIViewController+.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CounterView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomSegmentControlView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Enums/SegmentType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/SegmentButtonFactory.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/SheetUtils.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Controller/ModalViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Model/ModalInfo.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/View/ModalView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/View/SegmentControlStackView.swift
Labels: 🫐 feature, 🍓 수민, ❤️‍🩹 멍청이슈

#23 [FEAT] 마이투썸 셀 순서 이동 구현 (#22)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/Cell/MyMenuCollectionViewCell.swift
Labels: 🫐 feature, 🍓 수민

#26 [FEAT] 메뉴 UI 구현 (#19)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Application/SceneDelegate.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/PaddedLabel.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Base/BaseNavViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/Controller/MenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/Model/Menu.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/FooterView/MyButton.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/FooterView/SelectedStoreView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/HeaderView/MenuCategoryView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/HeaderView/MenuSubcategoryView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/TableViewCell/MenuCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/Type/MenuCategoryType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/View/Type/MenuSubcategoryType.swift
Labels: 🫐 feature, 🍍범수

#27 [FEAT] 모달 뷰 즐겨찾기 API 연결 및 토스트 구현 (#24)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomSegmentControlView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/ToastController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Controller/ModalViewController.swift
Labels: 🫐 feature, 🍓 수민

#28 [FEAT] 메뉴 상세정보 GET API 연동 (#25)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS.xcodeproj/project.pbxproj
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/APITarget/APITarget+Menu.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/DTO/Response/DTO+GetMenuInfoResponse.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/Controller/MenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/Model/Menu.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Controller/MenuDetailViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Model/MenuDetail.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Type/CautionType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Type/MenuStatusType.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/MenuInfoTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/NutritionHeaderTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/NutritionInfoTableViewCell.swift
Labels: 🫐 feature, 🍒 예지

#31 [FEAT] 마이 메뉴 즐겨찾기 목록 API 연동 (#29)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/Aliases.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/Utils/StringLiterals.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/DTO/Response/DTO+GetLikedMenuResponse.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/Menu/Controller/MenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/Cell/MyMenuCollectionViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuHeaderView.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuModalView.swift
Labels: 🫐 feature, 🍒 예지, ❤️‍🩹 멍청이슈

#33 [CHORE] 뷰 연결 및 QA 전 자잘한 마무리 (#32)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/ToastController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/Controller/MenuDetailViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/MenuInfoTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuOption/Controller/MenuOptionViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Controller/ModalViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Model/ModalInfo.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
Labels: ❄️ chore, 🍓 수민

#35 [FIX] QA 반영 (#34)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/APITarget/APITarget+Menu.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/DTO/Response/DTO+GetLikedMenuResponse.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MenuDetailView/View/Cell/MenuInfoTableViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/ModalView/Controller/ModalViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Model/MyMenuItem.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuModalView.swift
Labels: 🆘 fix, 🍓 수민

#36 [FEAT] 즐겨찾기 목록 삭제 API 연동 (#30)
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Global/UIComponents/CustomAlertViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/APITarget/APITarget+Likes.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Network/DTO/Request/DTO+DeleteLikedMenuRequest.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/Controller/MyMenuViewController.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/Cell/MyMenuCollectionViewCell.swift
  TWOSOMEHEART-iOS/TWOSOMEHEART-iOS/Presentation/MyMenuView/View/MyMenuHeaderView.swift
Labels: 🫐 feature, 🍓 수민
